version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  deteccion-caras-python:
    lang: python3-http-debian
    handler: ./deteccion-caras-python
    image: iamlassy/deteccion-caras-python:latest
    environment:
      write_debug: true
